name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Deploy
        run: |
          set -x
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.DOKKU_HOST }}>> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.DOKKU_SSH_PRIVATE_KEY}}"
          ssh dokku@${{ secrets.DOKKU_HOST }} -C dokku apps:create APP_NAME || true
          ssh dokku@${{ secrets.DOKKU_HOST }} -C dokku builder:set APP_NAME build-dir src
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku builder-dockerfile:set APP_NAME dockerfile-path Dockerfile"
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku config:set --no-restart APP_NAME RAILS_DEVELOPMENT_HOSTS=APP_NAME.containers.anotherwebservice.com"
          # Database connection string (rails)
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku config:set --no-restart APP_NAME DATABASE_URL=${{ secrets.RAILS_DATABASE_URL }}"
          # Database connection string (django)
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku config:set --no-restart APP_NAME DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY}}"
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku config:set --no-restart APP_NAME DEBUG=${{ secrets.DJANGO_DEBUG}}"
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku config:set --no-restart APP_NAME DB_ENGINE=${{ secrets.DJANGO_ENGINE}}"
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku config:set --no-restart APP_NAME DB_NAME=${{ secrets.DJANGO_DB_NAME}}"
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku config:set --no-restart APP_NAME DB_USER=${{ secrets.DJANGO_DB_USER}}"
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku config:set --no-restart APP_NAME DB_PASSWORD=${{ secrets.DJANGO_DB_PASSWORD}}"
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku config:set --no-restart APP_NAME DB_PORT=${{ secrets.DJANGO_DB_PORT}}"

          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku git:sync --build APP_NAME" https://github.com/GITHUB_OWNER/REPO_NAME.git main
          # Assign letsencrypt wildcard certificate
          ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku certs:add APP_NAME < cert-key.tar"

