name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deploy:
    environment: production
    runs-on: ubuntu-latest
    env:
      AMBER_SECRET: ${{ secrets.AMBER_SECRET }}
      DOKKU_SSH_PRIVATE_KEY: ${{ secrets.DOKKU_SSH_PRIVATE_KEY}}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Deploy
        run: |
          ./.container-hosting/deploy.sh
