services:
  app:
    image: container-sakfgls
    stdin_open: true
    tty: true
    build:
      context: ./src
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app
